# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches:
      - main
      - na44
      - na45
      - gs0
    types: 
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  backport:
#     if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Backport
    steps:
      - name: trigger single Job
        uses: appleboy/jenkins-action@master
        with:
          url: "http://example.com"
          user: "example"
          token: ${{ secrets.TOKEN }}
          job: "foobar"
